In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df=pd.read_csv('train.csv')

In [10]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
df.shape

(891, 12)

In [12]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
df['PassengerId'].nunique()
df.drop(['PassengerId','Cabin'],axis=1,inplace=True)

In [14]:
df.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      2
dtype: int64

In [15]:
df['Age'].value_counts()

24.00    30
22.00    27
18.00    26
28.00    25
19.00    25
         ..
55.50     1
74.00     1
0.92      1
70.50     1
12.00     1
Name: Age, Length: 88, dtype: int64

In [16]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df.isnull().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    2
dtype: int64

In [17]:
df.dropna(inplace=True)

In [18]:
df.shape

(889, 10)

In [19]:
df.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Embarked'],
      dtype='object')

In [20]:
df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [21]:
df['Survived'].value_counts()

0    549
1    340
Name: Survived, dtype: int64

In [22]:
df['Name'].nunique()
df.drop(['Name'],axis=1,inplace=True)

In [23]:
print(df['Sex'].value_counts())

male      577
female    312
Name: Sex, dtype: int64


In [24]:
print(df['SibSp'].value_counts())

0    606
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64


In [25]:
print(df['Parch'].value_counts())

0    676
1    118
2     80
3      5
5      5
4      4
6      1
Name: Parch, dtype: int64


In [26]:
df['Ticket'].nunique()

680

In [27]:
df.drop(['Ticket'],axis=1,inplace=True)
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [28]:
df.dtypes

Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Embarked     object
dtype: object

In [29]:
from sklearn.preprocessing import LabelEncoder

In [30]:
lb=LabelEncoder()
df['Embarked']=lb.fit_transform(df['Embarked'])
df['Sex']=lb.fit_transform(df['Sex'])

In [31]:
df.dtypes

Survived      int64
Pclass        int64
Sex           int32
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Embarked      int32
dtype: object

#### Model Building

In [32]:
x=df.drop('Survived',axis=1)
y=df['Survived']
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(889, 7)
(889,)


In [33]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(666, 7)
(223, 7)
(666,)
(223,)


In [36]:
def gen_cls_metrics(ytest,ypred):
    print('Accuracy Score',accuracy_score(ytest,ypred))
    cm=confusion_matrix(ytest,ypred)
    print(cm)
    print(classification_report(ytest,ypred))

def train_test_score(model):
    print('Training Score',model.score(x_train,y_train))
    print('Testing Score',model.score(x_test,y_test))

### Decision Tree Classifier

In [40]:
m1=DecisionTreeClassifier(criterion='gini',max_depth=5)
m1.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [41]:
train_test_score(m1)

Training Score 0.8513513513513513
Testing Score 0.8385650224215246


In [42]:
ypred_m1=m1.predict(x_test)
print(ypred_m1)

[0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 0 1 0 0 0 1 0 1 0 0
 1 1 1 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0
 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1
 1 0 1 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1
 1]


In [43]:
print('Metrics for Decision Tree Classifier')
gen_cls_metrics(y_test,ypred_m1)

Metrics for Decision Tree Classifier
Accuracy Score 0.8385650224215246
[[128  15]
 [ 21  59]]
              precision    recall  f1-score   support

           0       0.86      0.90      0.88       143
           1       0.80      0.74      0.77        80

    accuracy                           0.84       223
   macro avg       0.83      0.82      0.82       223
weighted avg       0.84      0.84      0.84       223



#### Random Forest Classifier

In [34]:
m2=RandomForestClassifier(n_estimators=70,criterion='gini',max_depth=5)
m2.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, n_estimators=70)

In [35]:
train_test_score(m2)

Training Score 0.8618618618618619
Testing Score 0.7847533632286996


In [36]:
ypred_m2=m2.predict(x_test)
print(ypred_m2)

[0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0
 1 0 0 0 1 1 0 1 0 0 0 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0 1 1 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0
 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1
 0]


In [37]:
print('Metrics for Random Forest Classifier')
gen_cls_metrics(y_test,ypred_m2)

Metrics for Random Forest Classifier
Accuracy Score 0.7892376681614349
[[120  14]
 [ 33  56]]
              precision    recall  f1-score   support

           0       0.78      0.90      0.84       134
           1       0.80      0.63      0.70        89

    accuracy                           0.79       223
   macro avg       0.79      0.76      0.77       223
weighted avg       0.79      0.79      0.78       223



#### KNN

In [38]:
m3=KNeighborsClassifier(n_neighbors=25)
m3.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=25)

In [39]:
train_test_score(m3)

Training Score 0.8618618618618619
Testing Score 0.7847533632286996


In [40]:
ypred_m3=m3.predict(x_test)
print(ypred_m3)

[0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0
 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 1
 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0
 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1
 0]


In [41]:
print('KNN')
gen_cls_metrics(y_test,ypred_m3)

KNN
Accuracy Score 0.7130044843049327
[[120  14]
 [ 50  39]]
              precision    recall  f1-score   support

           0       0.71      0.90      0.79       134
           1       0.74      0.44      0.55        89

    accuracy                           0.71       223
   macro avg       0.72      0.67      0.67       223
weighted avg       0.72      0.71      0.69       223



#### Logistic Regression

In [37]:
m4=LogisticRegression(max_iter=10000)
m4.fit(x_train,y_train)

LogisticRegression(max_iter=10000)

In [44]:
train_test_score(m4)

Training Score 0.8513513513513513
Testing Score 0.8385650224215246


In [45]:
ypred_m4=m4.predict(x_test)
print(ypred_m4)

[0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 1 1 1 1 0 0 0 0 1 0 0
 1 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0
 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1
 1 0 1 0 1 1 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0 0 0 1
 1]


In [46]:
print('Logistic Regression')
gen_cls_metrics(y_test,ypred_m4)

Logistic Regression
Accuracy Score 0.7982062780269058
[[119  24]
 [ 21  59]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       143
           1       0.71      0.74      0.72        80

    accuracy                           0.80       223
   macro avg       0.78      0.78      0.78       223
weighted avg       0.80      0.80      0.80       223



#### SVM

In [46]:
m5=SVC(kernel='linear',C=1)
m5.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [50]:
train_test_score(m5)

Training Score 0.8618618618618619
Testing Score 0.7847533632286996


In [51]:
ypred_m5=m5.predict(x_test)
print(ypred_m5)

[0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0
 1 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 1 0 0 1 0 1 1 0 0 0 1 1 1 0
 1 0 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0
 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1
 0]


In [52]:
print('Metrics for SVM Classifier')
gen_cls_metrics(y_test,ypred_m5)

Metrics for SVM Classifier
Accuracy Score 0.7309417040358744
[[109  25]
 [ 35  54]]
              precision    recall  f1-score   support

           0       0.76      0.81      0.78       134
           1       0.68      0.61      0.64        89

    accuracy                           0.73       223
   macro avg       0.72      0.71      0.71       223
weighted avg       0.73      0.73      0.73       223

